
language: generic
# Super User level permision
sudo: required
# Install a copy of docker
services:
  - docker
# Set-up and build a our testing docker image from Dockerfile.dev
before_install:
  - docker build -t miguelfrutos/docker-react -f Dockerfile.dev .
# Tell Travis how to run our test suite and exit (-e)
script:
  - docker run -e CI=true USERNAME/docker-react npm run test